source "https://rubygems.org"

gem "sidekiq"
gem "pry"
gem "aws-sdk", "~> 2"
gem "mysql2"
gem "activerecord"
gem "net-scp"
gem "net-ssh"
gem "rbvmomi"
gem "winrm"
gem "actionmailer"
gem "composite_primary_keys", "=9.0.6"
gem "fcm"
gem "azure"
gem "azure_mgmt_compute"
gem "rugged"
gem "rufus-scheduler"
gem "tzinfo-data"
gem "savon", "~> 2.0"
gem "net-ldap"
